# Generated by Django 5.2.4 on 2025-07-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_remove_recipe_author_recipe_image_alter_recipe_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
