# Generated by Django 5.2.4 on 2025-07-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_rename_body_comment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recette',
        ),
    ]
