# Generated by Django 5.2.4 on 2025-07-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0008_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
