# Generated by Django 5.2.4 on 2025-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.CharField(choices=[('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default=12, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.CharField(choices=[('terrasse', 'Terrasse'), ('interieur', "À l'intérieur")], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
